// Export helpers for a saved trip. Two formats:
//   - markdown: human-readable, paste-into-Notion-friendly
//   - json:     full structured trip for backup / re-import
//
// Both produce a Blob and trigger a browser download. Returning the blob
// also lets callers pipe to clipboard or share APIs without duplicating
// the serialisation logic.

function safeFileName(name) {
  return (name || "trip")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60) || "trip";
}

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Convert a saved trip into a clean, readable markdown document.
 */
export function tripToMarkdown(trip) {
  if (!trip) return "";
  const lines = [];
  const title = trip.tripTitle || trip.input?.destination || "Trip plan";
  lines.push(`# ${title}`);
  lines.push("");
  if (trip.input?.destination) {
    lines.push(`**Destination:** ${trip.input.destination}`);
  }
  const meta = [
    trip.days?.length ? `${trip.days.length} days` : null,
    trip.input?.travelers
      ? `${trip.input.travelers} ${trip.input.travelers === 1 ? "traveler" : "travelers"}`
      : null,
    trip.input?.budget ? `${trip.input.budget} budget` : null,
    trip.input?.travelStyle ? `${trip.input.travelStyle} pace` : null,
  ].filter(Boolean);
  if (meta.length) lines.push(`**Trip:** ${meta.join(" · ")}`);
  if (trip.totalEstimatedBudget)
    lines.push(`**Estimated budget:** ${trip.totalEstimatedBudget}`);
  if (trip.bestTimeToVisit)
    lines.push(`**Best time to visit:** ${trip.bestTimeToVisit}`);
  if (trip.summary) {
    lines.push("");
    lines.push(trip.summary);
  }

  if (trip.days?.length) {
    lines.push("");
    lines.push("## Itinerary");
    for (const day of trip.days) {
      lines.push("");
      lines.push(`### Day ${day.day} — ${day.title}`);
      if (day.estimatedCost) lines.push(`_Estimated cost: ${day.estimatedCost}_`);
      lines.push("");
      for (const a of day.activities ?? []) {
        const time = a.time ? `**${a.time}** — ` : "";
        const loc = a.location ? ` _(${a.location})_` : "";
        const cost = a.estimatedCost ? ` · ${a.estimatedCost}` : "";
        lines.push(`- ${time}${a.activity}${loc}${cost}`);
        if (a.description) lines.push(`  ${a.description}`);
      }
      if (day.foodRecommendations?.length) {
        lines.push("");
        lines.push("**Eat:**");
        for (const f of day.foodRecommendations) lines.push(`- ${f}`);
      }
    }
  }

  if (trip.hotels?.length) {
    lines.push("");
    lines.push("## Where to stay");
    for (const h of trip.hotels) {
      lines.push("");
      lines.push(`**${h.name}**${h.type ? ` · ${h.type}` : ""}`);
      if (h.priceRange) lines.push(`Price: ${h.priceRange}`);
      if (h.reason) lines.push(h.reason);
    }
  }

  const t = trip.transportation;
  if (t && (t.localTransport || t.interCity || t.tips?.length)) {
    lines.push("");
    lines.push("## Getting around");
    if (t.localTransport) lines.push(`**Local:** ${t.localTransport}`);
    if (t.interCity) lines.push(`**Inter-city:** ${t.interCity}`);
    if (t.tips?.length) {
      lines.push("");
      lines.push("**Tips:**");
      for (const tip of t.tips) lines.push(`- ${tip}`);
    }
  }

  if (trip.travelTips?.length) {
    lines.push("");
    lines.push("## Travel tips");
    for (const tip of trip.travelTips) lines.push(`- ${tip}`);
  }

  if (trip.packingList?.length) {
    lines.push("");
    lines.push("## Packing list");
    for (const item of trip.packingList) lines.push(`- [ ] ${item}`);
  }

  lines.push("");
  lines.push(`_Generated by Adventure.AI on ${new Date(trip.generatedAt || Date.now()).toLocaleDateString()}._`);
  return lines.join("\n");
}

export function downloadTripAsMarkdown(trip) {
  if (!trip) return;
  const md = tripToMarkdown(trip);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  triggerDownload(blob, `${safeFileName(trip.tripTitle || trip.input?.destination)}.md`);
}

export function downloadTripAsJSON(trip) {
  if (!trip) return;
  const blob = new Blob([JSON.stringify(trip, null, 2)], {
    type: "application/json",
  });
  triggerDownload(blob, `${safeFileName(trip.tripTitle || trip.input?.destination)}.json`);
}

export async function copyTripAsMarkdown(trip) {
  if (!trip) return false;
  try {
    await navigator.clipboard.writeText(tripToMarkdown(trip));
    return true;
  } catch {
    return false;
  }
}

/**
 * Build a Google Maps URL for the activity's location, scoped to the
 * destination so ambiguous place names ("Old Town") still resolve to the
 * right city.
 */
export function mapsUrlFor(location, destination) {
  if (!location) return null;
  const query = destination ? `${location}, ${destination}` : location;
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;
}
